set nocompatible              " required
filetype off                  " required

" cleanup of ~
if !has('nvim')
    set viminfo+=n~/.vim/viminfo
endif

packadd minpac
call minpac#init()

call minpac#add('altercation/vim-colors-solarized')
call minpac#add('chriskempson/base16-vim')
call minpac#add('christoomey/vim-tmux-navigator')
call minpac#add('k-takata/minpac', {'type':'opt'})
call minpac#add('kana/vim-textobj-entire')
call minpac#add('kana/vim-textobj-user')
call minpac#add('machakann/vim-highlightedyank')
call minpac#add('preservim/vimux')
call minpac#add('tmhedberg/SimpylFold')
call minpac#add('tpope/vim-commentary')
call minpac#add('tpope/vim-surround')
call minpac#add('vim-scripts/indentpython.vim')
call minpac#add('vim-syntastic/syntastic')
call minpac#add('ycm-core/YouCompleteMe')
" call minpac#add('nvie/vim-flake8')

" minpac commands:
command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()

set t_Co=256
syntax enable
if has('gui_running')
    set background=light
else
    set background=dark
endif

"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0
"
" Run command in  Vimux
" More such bindings can be found at https://www.bugsnag.com/blog/tmux-and-vim
let mapleader = ","
map <leader>vp :VimuxPromptCommand<cr>

let g:syntastic_python_checkers = ['flake8']
let g:syntastic_python_flake8_args = '--ignore=E221,E241,E251'

"if commented out colorscheme will be taken from shell
colorscheme solarized
highlight LineNr ctermfg=102
highlight link jsonNumber javaScriptNumber
highlight link jsonBoolean javaScriptFunction
highlight link pythonOperator pythonExClass

set encoding=utf-8
set fileencoding=utf-8

set foldmethod=syntax

set laststatus=1
set ruler
set number
set tabstop=8
set softtabstop=4
set shiftwidth=4
set expandtab
set incsearch
set hlsearch
set ignorecase
set smartcase
set autoindent
set smartindent
set nostartofline
set noswapfile
set scrolloff=3
set clipboard=unnamed

" Neovim only options
if has('nvim')
    set inccommand=split
endif

" Vim only options
if !has('nvim')
    map y <Plug>(highlightedyank)
endif

" Easier split navigation
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
" Easy folding
" nnoremap <space> za

autocmd StdinReadPre * let s:std_in=1
" make .brik and .mbrik documents open with latex coloring
autocmd BufNewFile,BufRead *.brik set filetype=tex syntax=tex
autocmd BufNewFile,BufRead *.mbrik set filetype=tex syntax=tex

" Additional comment strings for vim-commentary
autocmd FileType tex setlocal commentstring=\%\ %s

" lilypond
filetype off
set runtimepath+=/usr/local/share/lilypond/current/vim/
filetype on
syntax on
