#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi


# var for colortheme of qt apps
export QT_QPA_PLATFORMTHEME=gtk2

# start window manager
exec i3
