#!/bin/sh

export PATH=${PATH}:${SCRIPT_DIR}:/usr/sbin/:${HOME}/Jts/:${HOME}/portfolio/
# check if Xresources exists and if so rebuild X resources database
[ -f ${SCRIPT_DIR}/settheme ] && [ -f ${SCRIPT_DIR}/current_theme ] &&
    bd=$(${SCRIPT_DIR}/current_theme); ${SCRIPT_DIR}/settheme $bd

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.

pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1


# remap keys
remaps &
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

autostart="mpd dunst unclutter fcitx5"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
